### ISSUE TITLE
Tuner not responding to button inputs in the tuner module

### ISSUE THREAD

**Issue by ardugnome** [Efpophis/LDGControl#2]
Buttons not responding to clicks:

1. Antenna 1
2. Bypass
3. Full Tune
4. Memory Tune

They work in ver 1.2.0 -1.6.0.2

**Comment by Efpophis** [comment]
That's weird, I just used the latest version this morning myself and the memory tune button worked fine.

I know the buttons are grayed out and disabled until initialization is complete, tho. Is it possible your serial port changed and initialization is failing? I did have an issue like that where the USB serial device got changed to a different port and the program looked like it had initialized ok, but it was trying to talk to a different device, so nothing worked. I should probably add some code to make sure it's talking to an ldg tuner on init.

I'll hold this issue open until we get things figured out - please feel free to reach out to me via email directly if you like.

**Comment by ardugnome** [comment]
Checked and my side still acts up. Will check again hardware. Seems like even 1.2 does not put tuner into bypass only flashes the function lights. Using a simple FTDI chip to USB, but will check baud rates. just in case. If it works for you, please close the issue.

**Comment by Efpophis** [comment]
I do know that the 'bypass' function on the tuner itself changed after a firmware update from LDG. It does appear to bypass, but it's not the same behavior as pressing the button on the tuner anymore. My software does still get the response, so I'm not sure what else there is to be done.

Did you figure out what was going on? I see you closed the issue..
